[package]
name = "greenhouse-rs"
version = "0.1.0"
authors = ["Wangweizhen <hawking.rei@gmail.com>"]
edition = "2018"

[dependencies]
brotli = "2.5"
clap = "2.32.0"
flate2 = "1.0.2"
lz4 = "1.23"
quick-error = "1.2.2"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
snap = "0.2"
zstd = "0.4.14"
rand = "0.4"
rocket-slog = "0.2.2"
sloggers = "0.3.1"
slog = "2.4.1"

[lib]
name = "greenhouse"

[[bin]]
name = "greenhouse-server"